### PR TITLE
Add subgroups to allow sorting within a group

### LINKED ISSUE #10: Feature request: Additional sorting functions
I would like to suggest some new features for the sorter:
- [ ] add an option to put the extended class + interfaces at the top (or top of the group)
- [ ] create a special group name `_annotations` which groups annotations (is that possible with the current implementation/in general?)
- [x] allow to combine groups like:

```yml
use-sort:
    group:
        - Symfony
        - _main
        - App
        - ['Sensio\Bundle\FrameworkExtraBundle\Configuration', 'JMS\DiExtraBundle\Annotation']
    group-type: each
    sort-type: alph
    sort-direction: asc
```

- [x] and ideally allow additional sorting within a group (like Symfony HttpKernel before Symfony Form e.g.)

Wdyt @mmoreram ?

### PR DESCRIPTION
**Pull request by hacfi**
Example .formatter.yml:
```yml
use-sort:
    group:
        - [Symfony\Component\HttpKernel, Symfony]
        - _main
        - App
```

to put Symfony\Component\HttpKernel classes on top of the group

Fixes #10

### CODE REVIEW

**Comment by hacfi** [comment]
Had a little rebase conflict because of my other PR but all fixed now.

Included a small test for both this PR and #12. Wasn’t sure how to test for no bc breaks but all previous tests passed!?

**Comment by hacfi** [comment]
@mmoreram anything missing?

**Comment by xphere** [comment]
ping @mmoreram :grin:

**Comment by hacfi** [comment]
RTM @mmoreram :grinning:

**Comment by mmoreram** [comment]
@hacfi Could you please document this feature? Ready to be merged...

**Comment by hacfi** [comment]
@mmoreram Sure. Just noticed that this feature can’t be used without the config or is there a way to pass an array as a cli argument?

**Comment by hacfi** [comment]
Fixed some typos while I was at it

**Comment by hacfi** [comment]
@xphere Will have a look on the weekend..I only had sub-namespaces in mind so didn’t check that.

**Comment by mmoreram** [comment]
Hmmm ok :) Please, fix asap as possible :')

**Comment by hacfi** [comment]
I don’t really understand the use-case but will try to fix it asap.

**Comment by mmoreram** [comment]
well, let's find out what the problem is, let's add some tests in order to make them fail, and then, let's fix it :dancer: 

ASk me some help if you need it ! :)

**Pull request merged**
